# Generated by Codex for extsync app

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_servicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='', max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('wws_order_no', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Order',
                'verbose_name_plural': 'External Orders',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('UPSERT_ORDER', 'UPSERT_ORDER'), ('GENERATE_DOCUMENT', 'GENERATE_DOCUMENT')], max_length=32)),
                ('dedupe_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('dead', 'dead')], default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('current', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
            },
        ),
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('QUOTE', 'QUOTE'), ('INVOICE', 'INVOICE')], max_length=16)),
                ('status', models.CharField(choices=[('creating', 'creating'), ('ready', 'ready'), ('failed', 'failed')], default='creating', max_length=16)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='extsync/documents/')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='extsync.externalorder')),
            ],
            options={
                'verbose_name': 'External Document',
                'verbose_name_plural': 'External Documents',
            },
        ),
        migrations.AddIndex(
            model_name='externalorder',
            index=models.Index(fields=['tenant', 'updated_at'], name='extsync_ord_tenant_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldocument',
            index=models.Index(fields=['tenant', 'status'], name='extsync_doc_tenant_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldocument',
            index=models.Index(fields=['tenant', 'order'], name='extsync_doc_tenant_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'run_at'], name='extsync_job_stat_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('tenant', 'dedupe_key'), name='uniq_job_dedupe_tenant'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_sequence_tenant_name'),
        ),
    ]
