# Generated by Django 5.2.9 on 2025-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billing_settings'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_tenant_status',
        ),
    ]
