# Generated by Django 5.2.9 on 2025-12-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billingsettings_tenant_alter_invoice_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='accent_color',
            field=models.CharField(default='#f3f4f6', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='address_layout',
            field=models.CharField(default='two-column', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='invoice_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='invoice_font',
            field=models.CharField(default='inter', max_length=50),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='invoice_template',
            field=models.CharField(default='clean', max_length=50),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='logo_position',
            field=models.CharField(default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='number_position',
            field=models.CharField(default='right', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='table_style',
            field=models.CharField(default='grid', max_length=20),
        ),
    ]
