# Generated by Django 5.2.9 on 2025-12-24 04:47

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0116_alter_stockitem_link'),
        ('tenancy', '0004_tenant_max_devices_tenant_max_users_tenantdevice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockitem',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
    ]
