# Generated by Django 5.2.9 on 2025-12-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('tenancy', '0004_tenant_max_devices_tenant_max_users_tenantdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='whatsappchannel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
    ]
