# Generated by Django 5.2.9 on 2025-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wws', '0003_merchants_settings'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_tenant_created',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_tenant_status',
        ),
    ]
