# Generated by Django 5.2.9 on 2025-12-24 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_devices',
            field=models.IntegerField(default=10, help_text='Maximum number of concurrent devices/sessions allowed for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Maximum number of users allowed for this tenant'),
        ),
        migrations.CreateModel(
            name='TenantDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Device',
                'verbose_name_plural': 'Tenant Devices',
                'unique_together': {('user', 'tenant', 'device_id')},
            },
        ),
    ]
